package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Friday, May 11, 2018 7:00:13 PM COT
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
